const wineData = [

    // ===================== RED WINES =====================
    {
        id: 'wine-001',
        category: 'red',
        name: 'Cabernet Sauvignon',
        brand: 'Château Reserve',
        origin: 'France',
        flag: '🇫🇷',
        alcohol: '13.5%',
        bottleSize: '750ml',
        price: 8500,
        rating: 4.9,
        reviews: 312,
        availability: 'available',
        tags: ['premium', 'chef-pick'],
        description: 'Full-bodied with rich black currant, cedar, and tobacco notes. Pairs beautifully with red meats and aged cheeses.',
        pairings: ['Steak', 'Lamb', 'Aged Cheese'],
        image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&q=80',
        vintage: '2019',
        type: 'Dry'
    },
    {
        id: 'wine-002',
        category: 'red',
        name: 'Merlot',
        brand: 'Bordeaux Estates',
        origin: 'France',
        flag: '🇫🇷',
        alcohol: '13.0%',
        bottleSize: '750ml',
        price: 6800,
        rating: 4.7,
        reviews: 245,
        availability: 'available',
        tags: ['popular'],
        description: 'Smooth and velvety with plum, chocolate, and herbal notes. An approachable red for any occasion.',
        pairings: ['Grilled Chicken', 'Pasta', 'Mushroom'],
        image: 'https://images.unsplash.com/photo-1474722883778-792e7990302f?w=400&q=80',
        vintage: '2020',
        type: 'Medium Dry'
    },
    {
        id: 'wine-003',
        category: 'red',
        name: 'Pinot Noir',
        brand: 'Burgundy Grand Cru',
        origin: 'France',
        flag: '🇫🇷',
        alcohol: '12.5%',
        bottleSize: '750ml',
        price: 9200,
        rating: 4.8,
        reviews: 198,
        availability: 'available',
        tags: ['premium', 'limited'],
        description: 'Elegant and light-bodied with cherry, raspberry, and earthy undertones. The sommelier\'s choice.',
        pairings: ['Duck', 'Salmon', 'Truffle'],
        image: 'https://images.unsplash.com/photo-1568213816046-0ee1c42bd559?w=400&q=80',
        vintage: '2018',
        type: 'Dry'
    },
    {
        id: 'wine-004',
        category: 'red',
        name: 'Shiraz',
        brand: 'Barossa Valley Select',
        origin: 'Australia',
        flag: '🇦🇺',
        alcohol: '14.0%',
        bottleSize: '750ml',
        price: 5900,
        rating: 4.6,
        reviews: 167,
        availability: 'available',
        tags: ['bold'],
        description: 'Bold and spicy with blackberry, pepper, and smoky oak. Perfect for BBQ and grilled meats.',
        pairings: ['BBQ', 'Grilled Steak', 'Spicy Food'],
        image: 'https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=400&q=80',
        vintage: '2021',
        type: 'Dry'
    },
    {
        id: 'wine-005',
        category: 'red',
        name: 'Malbec',
        brand: 'Mendoza Reserve',
        origin: 'Argentina',
        flag: '🇦🇷',
        alcohol: '13.8%',
        bottleSize: '750ml',
        price: 5400,
        rating: 4.5,
        reviews: 134,
        availability: 'available',
        tags: [],
        description: 'Rich and jammy with dark fruits, violet, and velvety tannins. Argentina\'s finest export.',
        pairings: ['Steak', 'Empanadas', 'Dark Chocolate'],
        image: 'https://images.unsplash.com/photo-1543418219-44e27370e34e?w=400&q=80',
        vintage: '2020',
        type: 'Dry'
    },
    {
        id: 'wine-006',
        category: 'red',
        name: 'Sula Rasa',
        brand: 'Sula Vineyards',
        origin: 'India',
        flag: '🇮🇳',
        alcohol: '12.5%',
        bottleSize: '750ml',
        price: 2200,
        rating: 4.4,
        reviews: 421,
        availability: 'available',
        tags: ['indian', 'popular'],
        description: 'India\'s beloved red blend — soft tannins, berry notes, and a smooth finish. Perfect for everyday luxury.',
        pairings: ['Indian Cuisine', 'Tandoori', 'Kebabs'],
        image: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=400&q=80',
        vintage: '2022',
        type: 'Semi Dry'
    },
    {
        id: 'wine-007',
        category: 'red',
        name: 'Grover La Réserve',
        brand: 'Grover Zampa',
        origin: 'India',
        flag: '🇮🇳',
        alcohol: '13.5%',
        bottleSize: '750ml',
        price: 3800,
        rating: 4.6,
        reviews: 289,
        availability: 'available',
        tags: ['indian', 'premium', 'chef-pick'],
        description: 'Aged in French oak barrels. Complex bouquet of red berries, vanilla, and subtle spice. Award-winning.',
        pairings: ['Roast Lamb', 'Biryani', 'Paneer Tikka'],
        image: 'https://images.unsplash.com/photo-1572362910954-8c8b0f6d7c0b?w=400&q=80',
        vintage: '2021',
        type: 'Dry'
    },
    {
        id: 'wine-008',
        category: 'red',
        name: 'Fratelli Sette',
        brand: 'Fratelli Wines',
        origin: 'India',
        flag: '🇮🇳',
        alcohol: '14.0%',
        bottleSize: '750ml',
        price: 4500,
        rating: 4.7,
        reviews: 156,
        availability: 'limited',
        tags: ['indian', 'limited', 'premium'],
        description: 'A bold Italian-Indian collaboration. Seven grape varieties blended into one exceptional wine. Rich, complex, unforgettable.',
        pairings: ['Slow Cooked Meat', 'Charcuterie', 'Hard Cheese'],
        image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80',
        vintage: '2020',
        type: 'Dry'
    },

    // ===================== WHITE WINES =====================
    {
        id: 'wine-009',
        category: 'white',
        name: 'Chardonnay',
        brand: 'Napa Valley Estate',
        origin: 'USA',
        flag: '🇺🇸',
        alcohol: '13.0%',
        bottleSize: '750ml',
        price: 7200,
        rating: 4.8,
        reviews: 378,
        availability: 'available',
        tags: ['premium', 'chef-pick'],
        description: 'Buttery and full-bodied with tropical fruit, vanilla, and toasted oak. The queen of white wines.',
        pairings: ['Lobster', 'Scallops', 'Creamy Pasta'],
        image: 'https://images.unsplash.com/photo-1584916201218-f4242ceb4809?w=400&q=80',
        vintage: '2020',
        type: 'Dry'
    },
    {
        id: 'wine-010',
        category: 'white',
        name: 'Sauvignon Blanc',
        brand: 'Marlborough Select',
        origin: 'New Zealand',
        flag: '🇳🇿',
        alcohol: '12.5%',
        bottleSize: '750ml',
        price: 6100,
        rating: 4.7,
        reviews: 301,
        availability: 'available',
        tags: ['popular'],
        description: 'Crisp and refreshing with grapefruit, passion fruit, and fresh herb aromas. Perfect for summer dining.',
        pairings: ['Seafood', 'Salads', 'Goat Cheese'],
        image: 'https://images.unsplash.com/photo-1612528443702-f6741f70a049?w=400&q=80',
        vintage: '2022',
        type: 'Dry'
    },
    {
        id: 'wine-011',
        category: 'white',
        name: 'Riesling',
        brand: 'Mosel Valley',
        origin: 'Germany',
        flag: '🇩🇪',
        alcohol: '10.5%',
        bottleSize: '750ml',
        price: 5800,
        rating: 4.6,
        reviews: 189,
        availability: 'available',
        tags: ['aromatic'],
        description: 'Floral and aromatic with peach, apricot, and a refreshing acidity. Exceptional with spicy cuisine.',
        pairings: ['Spicy Food', 'Asian Cuisine', 'Fruit Desserts'],
        image: 'https://images.unsplash.com/photo-1567529684892-09290a1b2d05?w=400&q=80',
        vintage: '2021',
        type: 'Off-Dry'
    },
    {
        id: 'wine-012',
        category: 'white',
        name: 'Pinot Grigio',
        brand: 'Alto Adige DOC',
        origin: 'Italy',
        flag: '🇮🇹',
        alcohol: '12.0%',
        bottleSize: '750ml',
        price: 5200,
        rating: 4.5,
        reviews: 223,
        availability: 'available',
        tags: [],
        description: 'Light and elegant with green apple, lemon zest, and almond notes. Ideal for light meals and aperitifs.',
        pairings: ['Light Pasta', 'Grilled Fish', 'Antipasti'],
        image: 'https://images.unsplash.com/photo-1566552881560-0be862a7c445?w=400&q=80',
        vintage: '2022',
        type: 'Dry'
    },
    {
        id: 'wine-013',
        category: 'white',
        name: 'Chenin Blanc',
        brand: 'Loire Valley',
        origin: 'France',
        flag: '🇫🇷',
        alcohol: '12.0%',
        bottleSize: '750ml',
        price: 5600,
        rating: 4.6,
        reviews: 145,
        availability: 'available',
        tags: ['versatile'],
        description: 'Honeyed and floral with quince, apple, and chamomile. Remarkably versatile across all food styles.',
        pairings: ['Foie Gras', 'Roast Chicken', 'Soft Cheese'],
        image: 'https://images.unsplash.com/photo-1510672981848-a1c4f1cb5ccf?w=400&q=80',
        vintage: '2021',
        type: 'Off-Dry'
    },
    {
        id: 'wine-014',
        category: 'white',
        name: 'Sula Chenin Blanc',
        brand: 'Sula Vineyards',
        origin: 'India',
        flag: '🇮🇳',
        alcohol: '12.0%',
        bottleSize: '750ml',
        price: 1800,
        rating: 4.5,
        reviews: 534,
        availability: 'available',
        tags: ['indian', 'popular', 'bestseller'],
        description: 'India\'s most celebrated white wine. Crisp tropical fruit, citrus blossom, and a clean refreshing finish.',
        pairings: ['Seafood', 'Grilled Vegetables', 'Paneer'],
        image: 'https://images.unsplash.com/photo-1578911373434-0297e4a14843?w=400&q=80',
        vintage: '2023',
        type: 'Dry'
    },
    {
        id: 'wine-015',
        category: 'white',
        name: 'Grover Viognier',
        brand: 'Grover Zampa',
        origin: 'India',
        flag: '🇮🇳',
        alcohol: '12.5%',
        bottleSize: '750ml',
        price: 2600,
        rating: 4.6,
        reviews: 198,
        availability: 'available',
        tags: ['indian', 'aromatic', 'premium'],
        description: 'Richly perfumed with apricot, peach, and rose petal aromas. A stunning expression of Indian terroir.',
        pairings: ['Prawn Curry', 'Thai Food', 'Mild Spices'],
        image: 'https://images.unsplash.com/photo-1587116861421-1cd3e8c7d47a?w=400&q=80',
        vintage: '2022',
        type: 'Dry'
    },

    // ===================== PREMIUM SPIRITS / VODKA =====================
    {
        id: 'spirit-001',
        category: 'vodka',
        name: 'Magic Moments Original',
        brand: 'Magic Moments',
        origin: 'India',
        flag: '🇮🇳',
        alcohol: '42.8%',
        bottleSize: '750ml',
        price: 1200,
        rating: 4.4,
        reviews: 678,
        availability: 'available',
        tags: ['bestseller', 'classic'],
        description: 'The original that started it all. Clean, smooth, and crystal clear — perfect neat or in cocktails.',
        pairings: ['Tonic Water', 'Fresh Lime', 'Cocktails'],
        image: 'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=400&q=80',
        vintage: null,
        type: 'Vodka'
    },
    {
        id: 'spirit-002',
        category: 'vodka',
        name: 'Magic Moments Verve',
        brand: 'Magic Moments',
        origin: 'India',
        flag: '🇮🇳',
        alcohol: '42.8%',
        bottleSize: '750ml',
        price: 1400,
        rating: 4.5,
        reviews: 445,
        availability: 'available',
        tags: ['premium', 'popular'],
        description: 'The premium ultra-pure expression. Triple distilled for unparalleled smoothness and a luxurious finish.',
        pairings: ['Martini', 'Moscow Mule', 'Soda'],
        image: 'https://images.unsplash.com/photo-1608885898957-a559228e8749?w=400&q=80',
        vintage: null,
        type: 'Vodka'
    },
    {
        id: 'spirit-003',
        category: 'vodka',
        name: 'Magic Moments Green Apple',
        brand: 'Magic Moments',
        origin: 'India',
        flag: '🇮🇳',
        alcohol: '37.5%',
        bottleSize: '750ml',
        price: 1100,
        rating: 4.3,
        reviews: 312,
        availability: 'available',
        tags: ['flavoured', 'popular'],
        description: 'A crisp burst of fresh green apple in every sip. Light, fruity, and perfect for summer cocktails.',
        pairings: ['Apple Juice', 'Ginger Beer', 'Lemonade'],
        image: 'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=400&q=80',
        vintage: null,
        type: 'Flavoured Vodka'
    },
    {
        id: 'spirit-004',
        category: 'vodka',
        name: 'Magic Moments Orange',
        brand: 'Magic Moments',
        origin: 'India',
        flag: '🇮🇳',
        alcohol: '37.5%',
        bottleSize: '750ml',
        price: 1100,
        rating: 4.2,
        reviews: 267,
        availability: 'available',
        tags: ['flavoured'],
        description: 'Bright citrus orange zest with a clean vodka base. A crowd-favourite at parties and lounges.',
        pairings: ['Orange Juice', 'Grenadine', 'Cocktails'],
        image: 'https://images.unsplash.com/photo-1560963805-6c64417abba7?w=400&q=80',
        vintage: null,
        type: 'Flavoured Vodka'
    },
    {
        id: 'spirit-005',
        category: 'vodka',
        name: 'Magic Moments Lemon',
        brand: 'Magic Moments',
        origin: 'India',
        flag: '🇮🇳',
        alcohol: '37.5%',
        bottleSize: '750ml',
        price: 1100,
        rating: 4.3,
        reviews: 198,
        availability: 'available',
        tags: ['flavoured'],
        description: 'Zesty fresh lemon with a smooth vodka finish. Ideal for lemon drops and summer spritzers.',
        pairings: ['Lemonade', 'Soda Water', 'Iced Tea'],
        image: 'https://images.unsplash.com/photo-1582197519878-b4b2f7a3b8c5?w=400&q=80',
        vintage: null,
        type: 'Flavoured Vodka'
    },
    {
        id: 'spirit-006',
        category: 'vodka',
        name: 'Magic Moments Raspberry',
        brand: 'Magic Moments',
        origin: 'India',
        flag: '🇮🇳',
        alcohol: '37.5%',
        bottleSize: '750ml',
        price: 1100,
        rating: 4.4,
        reviews: 223,
        availability: 'available',
        tags: ['flavoured', 'popular'],
        description: 'Luscious wild raspberry with a subtle sweetness. A favourite for cocktail lovers and lounge nights.',
        pairings: ['Cranberry Juice', 'Lime Soda', 'Raspberry Mojito'],
        image: 'https://images.unsplash.com/photo-1527661591475-527312dd65f5?w=400&q=80',
        vintage: null,
        type: 'Flavoured Vodka'
    },
    {
        id: 'spirit-007',
        category: 'vodka',
        name: 'Magic Moments Chocolate',
        brand: 'Magic Moments',
        origin: 'India',
        flag: '🇮🇳',
        alcohol: '37.5%',
        bottleSize: '750ml',
        price: 1200,
        rating: 4.5,
        reviews: 334,
        availability: 'available',
        tags: ['flavoured', 'indulgent', 'popular'],
        description: 'Rich dark chocolate meets premium vodka. A decadent indulgence for dessert cocktails and nightcap moments.',
        pairings: ['Chocolate Martini', 'Cream', 'Coffee Liqueur'],
        image: 'https://images.unsplash.com/photo-1511381939415-e44015466834?w=400&q=80',
        vintage: null,
        type: 'Flavoured Vodka'
    },
    {
        id: 'spirit-008',
        category: 'vodka',
        name: 'Magic Moments Remix',
        brand: 'Magic Moments',
        origin: 'India',
        flag: '🇮🇳',
        alcohol: '36.0%',
        bottleSize: '750ml',
        price: 950,
        rating: 4.1,
        reviews: 445,
        availability: 'available',
        tags: ['value', 'flavoured'],
        description: 'A fun, vibrant flavour remix — the party starter. Mix and match with your favourite mixers.',
        pairings: ['Energy Drink', 'Soda', 'Juice Mix'],
        image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=400&q=80',
        vintage: null,
        type: 'Flavoured Vodka'
    },
    {
        id: 'spirit-009',
        category: 'vodka',
        name: 'Mansion House French Brandy',
        brand: 'Mansion House',
        origin: 'India',
        flag: '🇮🇳',
        alcohol: '42.8%',
        bottleSize: '750ml',
        price: 1800,
        rating: 4.6,
        reviews: 320,
        availability: 'available',
        tags: ['popular', 'classic', 'manstonhouse', 'brandy'],
        description: 'Mansion House French Brandy (often referred to as Manston House) is a premium Indian-made brandy crafted with fine grape spirits aged in oak, providing a rich aroma and exceptionally smooth finish.',
        pairings: ['Warm Water', 'Ginger Ale', 'Cola'],
        image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=400&q=80',
        vintage: null,
        type: 'Brandy'
    },
    {
        id: 'spirit-010',
        category: 'vodka',
        name: 'Mansion House Gold Barrel Whisky',
        brand: 'Mansion House',
        origin: 'India',
        flag: '🇮🇳',
        alcohol: '42.8%',
        bottleSize: '750ml',
        price: 2200,
        rating: 4.4,
        reviews: 185,
        availability: 'available',
        tags: ['premium', 'manstonhouse', 'whisky'],
        description: 'Mansion House Gold Barrel Whisky (commonly searched as Manston House) features a blend of premium Scotch malts and select Indian grain spirits, displaying soft peatiness with hints of vanilla and spice.',
        pairings: ['Ice', 'Soda', 'Water'],
        image: 'https://images.unsplash.com/photo-1527061011665-3652c757a4d4?w=400&q=80',
        vintage: null,
        type: 'Whisky'
    }
];
